apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nodeport
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-nodeport
  template:
    metadata:
      labels:
        app: web-nodeport
    spec:
      containers:
      - name: nginx
        image: nginxdemos/hello:latest
        ports:
          - containerPort: 80