apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress-hostname
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: website-a.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-a-svc
            port:
              number: 80
  - host: website-b.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-b-svc
            port:
              number: 80
      
      
          