apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-app
  template:
    metadata:
      labels:
        app: memory-app
    spec:
      containers:
      - name: memory-app-container
        image: nginx:latest
        resources:
          requests:
            cpu: "100m"
            memory: "64Mi"
        