apiVersion: v1
kind: Service
metadata:
  name: app-a-svc
spec:
  selector:
    app: app-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: app-b-svc
spec:
  selector:
    app: app-b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
